12/11/2014 19:01:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'test': folder could not be found in './user/'.
12/12/2014 23:54:59 WARNING nemoa.log -> attribute '%s' is not writeable.
12/19/2014 16:48:00 WARNING nemoa.log -> could not interpret "i3 + i4".
12/19/2014 16:48:00 WARNING nemoa.log -> could not interpret "i1 + i2".
12/19/2014 16:48:14 WARNING nemoa.log -> could not interpret "(i3 + i4)".
12/19/2014 16:48:14 WARNING nemoa.log -> could not interpret "(i1 + i2)".
12/23/2014 16:08:59 ERROR nemoa.log -> could not evaluate system unit relation: unknown algorithm name 'cooperation'.
12/23/2014 16:08:59 ERROR File "/usr/bin/ipython", line 5, in <module>->   start_ipython()
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 565, in launch_instance->   app.start()
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 371, in start->   self.shell.mainloop()
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2833, in run_ast_nodes->   if self.run_code(code):
12/23/2014 16:08:59 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/23/2014 16:08:59 ERROR File "<ipython-input-3-1da1bef31d8e>", line 1, in <module>->   model.evaluate('system', 'relations', 'cooperation')
12/23/2014 16:08:59 ERROR File "./package/nemoa/model/classes/base.py", line 408, in evaluate->   return self.system.evaluate(data, *args, **kwargs)
12/23/2014 16:08:59 ERROR File "./package/nemoa/system/classes/base.py", line 901, in evaluate->   return self._evaluate_relation(data, *args[1:], **kwargs)
12/23/2014 16:08:59 ERROR File "./package/nemoa/system/classes/base.py", line 1115, in _evaluate_relation->   unknown algorithm name '%s'.""" % (func))
12/23/2014 16:08:59 ERROR File "./package/nemoa/__init__.py", line 31, in log->   return nemoa.common.log.log(*args, **kwargs)
12/23/2014 16:08:59 ERROR File "./package/nemoa/common/log.py", line 174, in log->   for line in traceback.format_stack():
12/23/2014 16:20:11 WARNING nemoa.log -> could not get configuration: dataset with name 'multiplication' is not found in common workspace 'unittest'.
12/23/2014 16:20:11 ERROR nemoa.log -> could not import dataset: workspace 'None' does not contain a dataset with name 'multiplication'.
12/23/2014 16:20:11 ERROR File "/usr/bin/ipython", line 5, in <module>->   start_ipython()
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 565, in launch_instance->   app.start()
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 371, in start->   self.shell.mainloop()
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes->   if self.run_code(code):
12/23/2014 16:20:11 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/23/2014 16:20:11 ERROR File "<ipython-input-15-1d51092bdcf7>", line 1, in <module>->   model = nemoa.model.create(dataset = 'multiplication', network = network, system = 'dbn')
12/23/2014 16:20:11 ERROR File "./package/nemoa/model/__init__.py", line 22, in create->   return new(**build(*args, **kwargs))
12/23/2014 16:20:11 ERROR File "./package/nemoa/model/__init__.py", line 14, in build->   return nemoa.model.builder.build(*args, **kwargs)
12/23/2014 16:20:11 ERROR File "./package/nemoa/model/builder/__init__.py", line 38, in build->   model = nemoa.model.builder.base.build(type, *args, **kwargs)
12/23/2014 16:20:11 ERROR File "./package/nemoa/model/builder/base.py", line 20, in build->   if type == 'model': return Model(**kwargs).build()
12/23/2014 16:20:11 ERROR File "./package/nemoa/model/builder/base.py", line 79, in build->   = nemoa.dataset.load(self.settings['dataset'])
12/23/2014 16:20:11 ERROR File "./package/nemoa/dataset/__init__.py", line 27, in load->   return nemoa.dataset.imports.load(*args, **kwargs)
12/23/2014 16:20:11 ERROR File "./package/nemoa/dataset/imports/__init__.py", line 44, in load->   '%s'.""" % (workspace, path))
12/23/2014 16:20:11 ERROR File "./package/nemoa/__init__.py", line 31, in log->   return nemoa.common.log.log(*args, **kwargs)
12/23/2014 16:20:11 ERROR File "./package/nemoa/common/log.py", line 174, in log->   for line in traceback.format_stack():
